# File: pipelines/azure-pipelines-adf.yml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - adfdevm77kkznmognla/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - adfdevm77kkznmognla/**

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: "ServiceConnectionDevProd"

  # Resource groups
  devRg: "dev-analytics-finance"
  prodRg: "prod-analytics-finance"

  # Data Factory names (from each environment)
  devDataFactoryName: "adfdevm77kkznmognla"
  prodDataFactoryName: "adfprodpob5am325bfto"

  # SQL Server names (override linked service)
  devSqlServer: "sqldevm77kkznmognla.database.windows.net"
  prodSqlServer: "sqlprodpob5am325bfto.database.windows.net"

  # Storage URLs (override linked service)
  devRawContainerUrl: "https://stadevm77kkznmognla.dfs.core.windows.net/"
  prodRawContainerUrl: "https://staprodpob5am325bfto.dfs.core.windows.net/"

  # Path to published ARM templates
  adfPublishPath: "$(System.DefaultWorkingDirectory)/adfdevm77kkznmognla"

stages:
  - stage: Dev
    displayName: "Deploy Data Factory - Dev"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: Deploy_Dev
        displayName: "Deploy ADF (Dev)"
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: "az deployment group create (Dev)"
            inputs:
              azureSubscription: "$(azureSubscription)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                echo "Deploying ADF publish template to DEV..."
                az deployment group create \
                  --name deploy-adf-dev-$(Build.BuildId) \
                  --resource-group "$(devRg)" \
                  --template-file "$(adfPublishPath)/ARMTemplateForFactory.json" \
                  --parameters "$(adfPublishPath)/ARMTemplateParametersForFactory.json" \
                  --parameters \
                      factoryName="$(devDataFactoryName)" \
                      StagingDatabase_properties_typeProperties_server="$(devSqlServer)" \
                      StagingRawContainer_properties_typeProperties_url="$(devRawContainerUrl)"
                echo "✅ ADF Dev deployment completed."

  - stage: Prod
    displayName: "Deploy Data Factory - Prod"
    dependsOn: Dev
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'),
      in(dependencies.Dev.result, 'Succeeded'))
    jobs:
      - deployment: Deploy_Prod
        displayName: "Deploy ADF (Prod)"
        environment: "prod-adf"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: "az deployment group create (Prod)"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -euo pipefail
                      echo "Deploying ADF publish template to PROD..."
                      az deployment group create \
                        --name deploy-adf-prod-$(Build.BuildId) \
                        --resource-group "$(prodRg)" \
                        --template-file "$(adfPublishPath)/ARMTemplateForFactory.json" \
                        --parameters "$(adfPublishPath)/ARMTemplateParametersForFactory.json" \
                        --parameters \
                            factoryName="$(prodDataFactoryName)" \
                            StagingDatabase_properties_typeProperties_server="$(prodSqlServer)" \
                            StagingRawContainer_properties_typeProperties_url="$(prodRawContainerUrl)"
                      echo "✅ ADF Prod deployment completed."
